on:
  push:
    branches:
    - 'master'
    - '!badges'

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to test this action
    steps:

    # Get current banch name to use it as dest directory
    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> "${GITHUB_OUTPUT}"      

    - name: Prepare environment
      id: coverage
      env:
        COVERAGE: 53.5%
        BADGE_PATH: ${{ steps.extract_branch.outputs.branch }}/test-badge.svg
        BADGE1_PATH: ${{ steps.extract_branch.outputs.branch }}/test1-badge.svg
        BADGE2_PATH: ${{ steps.extract_branch.outputs.branch }}/test2-badge.svg
        BRANCH: badges
      run: |
        # Generates a GitHub Workflow output named `lines` with a coverage value
        echo "lines=${COVERAGE}" >> "${GITHUB_OUTPUT}"

        # Output values to be used by other steps
        echo "path=${BADGE_PATH}" >> "${GITHUB_OUTPUT}"
        echo "path1=${BADGE1_PATH}" >> "${GITHUB_OUTPUT}"
        echo "path2=${BADGE2_PATH}" >> "${GITHUB_OUTPUT}"
        echo "branch=${BRANCH}" >> "${GITHUB_OUTPUT}"

    - name: listPullRequests
      uses: buildsville/list-pull-requests@v1
      id: list
      with:
        token: ${{secrets.API_TOKEN}}
        skip_hour: '24'

    - name: exportingprlist
      id: prcount
      env: 
        pr_count_path: ${{ steps.extract_branch.outputs.branch }}/pr_count_badge.svg        
      run: |        
        echo "pr_Count=${pr_count_path}" >> "${GITHUB_OUTPUT}"

      

    - uses: actions/checkout@v3
      with:
        ref: ${{ steps.coverage.outputs.branch }}

    # Create the directory where badges will be saved, if needed
    - name: Create destination directory
      env:
        BADGE_PATH: ${{ steps.coverage.outputs.path }}
      run: mkdir -p "${BADGE_PATH%/*}"

    # Use the output from the `coverage` step
    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v2.0.2
      id: badge
      with:
        label: 'Test coverage'
        status: ${{ steps.coverage.outputs.lines }}
        color: 'blue,555,daf'
        path: ${{ steps.coverage.outputs.path }}

    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v2.0.2
      id: badge1
      with:
        label: 'Test1 coverage'
        status: ${{ steps.coverage.outputs.lines }}
        color: 'red,555,daf'
        path: ${{ steps.coverage.outputs.path1 }}

    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v2.0.2
      id: badge2
      with:
        label: 'Test2 coverage'
        status: ${{ steps.coverage.outputs.lines }}
        color: 'green,555,daf'
        path: ${{ steps.coverage.outputs.path2 }}

    - name: Generate the PR badge SVG image
      uses: emibcn/badge-action@v2.0.2
      id: badge3
      with:
        label: 'PR Count'
        status: ${{ steps.list.outputs.pulls }}
        color: 'green,555,daf'
        path: ${{ steps.prcount.outputs.pr_count }}            

    # - name: Upload badge as artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: badge
    #     path: ${{ steps.coverage.outputs.path }}
    #     if-no-files-found: error

    # - name: Upload badge1 as artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: badge
    #     path: ${{ steps.coverage.outputs.path1 }}
    #     if-no-files-found: error    

    - name: Commit badge
      continue-on-error: true
      env:
        BADGE: ${{ steps.coverage.outputs.path }}
        BADGE1: ${{ steps.coverage.outputs.path1 }}
        BADGE2: ${{ steps.coverage.outputs.path2 }}
        BADGE3: ${{ steps.prcount.outputs.pr_count }}

      run: |
        git config --local user.email "saibabu.tan@gmail.com"
        git config --local user.name "saiboby"
        git add "${BADGE}" "${BADGE1}" "${BADGE2}"  "{BADGE3}"
        git commit -m "Add/Update badge"
    - name: Push badge commit
      uses: ad-m/github-push-action@master
      if: ${{ success() }}
      with:
        github_token: ${{ secrets.API_TOKEN }}
        branch: ${{ steps.coverage.outputs.branch }}
